name: smartrotom_app
description: Una aplicación Pokémon revolucionaria para entrenadores.

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Versión más reciente
  firebase_auth: ^5.3.1   # Versión más reciente
  cloud_firestore: ^5.4.4  # Versión más reciente
  firebase_storage: ^12.3.3  # Versión más reciente
  http: ^1.0.0
  socket_io_client: ^3.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
